version: '3'
services:
  dim0517-api.rails.postgres.db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  dim0517-api.rails.web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - dim0517-api.rails.postgres.db
